name: Deploy Personal Bot to Aeza Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    environment:
      name: "Production"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log in to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/personal-bot:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"

    steps:
      - name: Deploy to aeza server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the latest image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/personal-bot:${{ github.sha }}

            # Check if the repository folder exists, if not clone it, otherwise fetch and checkout the specific commit
            if [ ! -d "personal-bot" ]; then
                mkdir personal-bot
            fi
            cd personal-bot

            # Create or update environment file
            touch .env
            echo "${{ vars.ENVS }}" > .env
            echo "${{ secrets.ENVS }}" >> .env

            docker run -d --restart always --env-file .env --name personal-bot ${{ secrets.DOCKERHUB_USERNAME }}/personal-bot:${{ github.sha }}
